name: Setup action
description: Setup build action

runs:
  using: "composite"
  steps:
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x86

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Setup depot tools
      uses: 2ndlab/actions/setup-depot-tools@main

    - name: Setup PATH and ENV
      shell: pwsh
      run: |
        echo "ANGLEStaticName=angle-x86-windows-static-chromium-$env:ANGLE_Branch-$env:UCRTVersion" >> $env:GITHUB_ENV
        echo "BuildDir=$env:GITHUB_WORKSPACE/out/windows/x86" >> $env:GITHUB_ENV
